In [21]:
import pandas as pd
import json

#json files were obtained from SpaceX API using Postman to GET the data

with open('f9_pastlaunches', 'r') as file1:
    launch_info_json = json.load(file1)

launch_info = pd.DataFrame(launch_info_json)


with open('coredata', 'r') as file2:
    core_json = json.load(file2)

core_info = pd.DataFrame(core_json)


with open('falcon9specs', 'r') as file3:
    f9_specs_json = json.load(file3)

f9_specs = pd.DataFrame([f9_specs_json])

In [25]:
launch_info

,flight_number,mission_name,mission_id,launch_year,launch_date_unix,launch_date_utc,launch_date_local,is_tentative,tentative_max_precision,tbd,...,timeline,crew,launch_failure_details,last_date_update,last_ll_launch_date,last_ll_update,last_wiki_launch_date,last_wiki_revision,last_wiki_update,launch_date_source
0,6,Falcon 9 Test Flight,[EE86F74],2010,1275677100,2010-06-04T18:45:00.000Z,2010-06-04T14:45:00-04:00,False,hour,False,...,"{'webcast_liftoff': 123, 'go_for_prop_loading'...",None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,7,COTS 1,[EE86F74],2010,1291822980,2010-12-08T15:43:00.000Z,2010-12-08T11:43:00-04:00,False,hour,False,...,"{'webcast_liftoff': 14, 'go_for_prop_loading':...",None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8,COTS 2,[EE86F74],2012,1335944640,2012-05-22T07:44:00.000Z,2012-05-22T03:44:00-04:00,False,hour,False,...,"{'webcast_liftoff': 42, 'go_for_prop_loading':...",None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9,CRS-1,[EE86F74],2012,1349656500,2012-10-08T00:35:00.000Z,2012-10-08T20:35:00-04:00,False,hour,False,...,"{'webcast_liftoff': 605, 'go_for_prop_loading'...",None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10,CRS-2,[EE86F74],2013,1362165000,2013-03-01T19:10:00.000Z,2013-03-01T15:10:00-04:00,False,hour,False,...,"{'webcast_liftoff': 2393, 'go_for_prop_loading...",None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,105,Starlink-14 (v1.0),[],2020,1603553460,2020-10-24T15:31:00.000Z,2020-10-24T11:31:00-04:00,False,hour,False,...,None,None,NaN,2020-10-22T22:36:44.000Z,None,None,2020-10-24T15:31:00.000Z,0f30530b-14b7-11eb-9724-0e4c83c0de3f,2020-10-22T22:36:44.000Z,wiki
97,106,GPS III SV04 (Sacagawea),[],2020,1604618640,2020-11-05T23:24:00.000Z,2020-11-05T18:24:00-05:00,False,hour,False,...,None,None,NaN,2020-11-02T12:13:58.000Z,None,None,2020-11-05T23:24:00.000Z,e21536bf-1d04-11eb-8908-0e0620cee639,2020-11-02T12:13:58.000Z,wiki
98,107,Crew-1,[EE86F74],2020,1605486420,2020-11-16T00:27:00.000Z,2020-11-15T19:27:00-05:00,False,hour,False,...,None,[],NaN,2020-11-13T21:31:19.000Z,None,None,2020-11-16T00:27:00.000Z,90e9da15-25f7-11eb-badd-0e3a392f3e47,2020-11-13T21:31:19.000Z,wiki
99,108,Sentinel-6 Michael Freilich,[],2020,1605979020,2020-11-21T17:17:00.000Z,2020-11-21T09:17:00-08:00,False,hour,False,...,None,None,NaN,2020-11-17T19:27:21.000Z,2020-11-21T17:17:00.000Z,2020-11-05T23:48:07.000Z,2020-11-21T17:17:00.000Z,e93220d1-290a-11eb-bd82-0e4885cc0cd7,2020-11-17T19:27:21.000Z,wiki
100,109,Starlink-15 (v1.0),[],2020,1603553460,2020-10-24T15:31:00.000Z,2020-10-24T11:31:00-04:00,False,hour,False,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
launchrows, launchcols = launch_info.shape

#Prints the number of rows and columns for the launch_info df
print(launchrows, launchcols)


column_headings1 = launch_info.columns.tolist()
print("Column headings:", column_headings1)

101 31
Column headings: ['flight_number', 'mission_name', 'mission_id', 'launch_year', 'launch_date_unix', 'launch_date_utc', 'launch_date_local', 'is_tentative', 'tentative_max_precision', 'tbd', 'launch_window', 'rocket', 'ships', 'telemetry', 'launch_site', 'launch_success', 'links', 'details', 'upcoming', 'static_fire_date_utc', 'static_fire_date_unix', 'timeline', 'crew', 'launch_failure_details', 'last_date_update', 'last_ll_launch_date', 'last_ll_update', 'last_wiki_launch_date', 'last_wiki_revision', 'last_wiki_update', 'launch_date_source']

In [27]:
core_info

,core_serial,block,status,original_launch,original_launch_unix,missions,reuse_count,rtls_attempts,rtls_landings,asds_attempts,asds_landings,water_landing,details
0,Merlin1A,NaN,lost,2006-03-24T22:30:00.000Z,1143239400,"[{'name': 'FalconSat', 'flight': 1}]",0,0,0,0,0,False,Engine failure at T+33 seconds resulted in los...
1,Merlin2A,NaN,lost,2007-03-21T01:10:00.000Z,1174439400,"[{'name': 'DemoSat', 'flight': 2}]",0,0,0,0,0,False,Successful first-stage burn and transition to ...
2,Merlin1C,NaN,lost,2008-08-03T03:34:00.000Z,1217734440,"[{'name': 'Trailblazer', 'flight': 3}]",0,0,0,0,0,False,Residual stage-1 thrust led to collision betwe...
3,Merlin2C,NaN,lost,2008-09-28T23:15:00.000Z,1222643700,"[{'name': 'RatSat', 'flight': 4}]",0,0,0,0,0,False,"Initially scheduled for 23â€“25 Sep, carried d..."
4,Merlin3C,NaN,lost,2009-07-13T03:35:00.000Z,1247456100,"[{'name': 'RazakSat', 'flight': 5}]",0,0,0,0,0,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,B1058,5.0,unknown,2020-05-30T19:22:00.000Z,1590866520,"[{'name': 'CCtCap Demo Mission 2', 'flight': 9...",2,0,0,2,2,False,"Landed on JRTI as of Jul 20, 2020"
65,B1060,5.0,unknown,2020-06-30T19:55:00.000Z,1593546900,"[{'name': 'GPS III SV03 (Columbus)', 'flight':...",2,0,0,3,3,False,"Landed on JRTI as of Jun 30, 2020."
66,B1062,5.0,None,2020-11-05T23:24:00.000Z,1604618640,"[{'name': 'GPS III SV04 (Sacagawea)', 'flight'...",0,0,0,1,1,False,None
67,B1061,5.0,None,2020-11-16T00:27:00.000Z,1605486420,"[{'name': 'Crew-1', 'flight': 107}]",0,0,0,1,1,False,None
68,B1063,5.0,None,2020-11-21T17:17:00.000Z,1605979020,"[{'name': 'Sentinel-6 Michael Freilich', 'flig...",0,1,1,0,0,False,None

In [31]:
corerows, corecols = core_info.shape

#Prints the number of rows and columns for the core_info df
print(corerows, corecols)

column_headings2 = core_info.columns.tolist()
print("Column headings:", column_headings2)

69 13
Column headings: ['core_serial', 'block', 'status', 'original_launch', 'original_launch_unix', 'missions', 'reuse_count', 'rtls_attempts', 'rtls_landings', 'asds_attempts', 'asds_landings', 'water_landing', 'details']

In [23]:
f9_specs

,id,active,stages,boosters,cost_per_launch,success_rate_pct,first_flight,country,company,height,...,first_stage,second_stage,engines,landing_legs,flickr_images,wikipedia,description,rocket_id,rocket_name,rocket_type
0,2,True,2,0,50000000,97,2010-06-04,United States,SpaceX,"{'meters': 70, 'feet': 229.6}",...,"{'reusable': True, 'engines': 9, 'fuel_amount_...","{'reusable': False, 'engines': 1, 'fuel_amount...","{'number': 9, 'type': 'merlin', 'version': '1D...","{'number': 4, 'material': 'carbon fiber'}",[https://farm1.staticflickr.com/929/2878733830...,https://en.wikipedia.org/wiki/Falcon_9,Falcon 9 is a two-stage rocket designed and ma...,falcon9,Falcon 9,rocket

In [32]:
specrows, speccols = f9_specs.shape

#Prints the number of rows and columns for the f9_specs df
print(specrows, speccols)

column_headings3 = f9_specs.columns.tolist()
print("Column headings:", column_headings3)

1 23
Column headings: ['id', 'active', 'stages', 'boosters', 'cost_per_launch', 'success_rate_pct', 'first_flight', 'country', 'company', 'height', 'diameter', 'mass', 'payload_weights', 'first_stage', 'second_stage', 'engines', 'landing_legs', 'flickr_images', 'wikipedia', 'description', 'rocket_id', 'rocket_name', 'rocket_type']